title: Compute General Lab
logo: /assets/img/logo.png
description: Compute General Lab (CGL) is a lab aimed to do compute architecture study and research, the research area including general computing, compute graphics, machine learning etc.
#show_downloads: true
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
