title: Compute General/Graphics Lab
logo: /assets/img/logo.png
description: Compute General/Graphics Lab (CGL) Home Page
#show_downloads: true
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
